### ISSUE TITLE
Invalid tag format should throw error

### ISSUE THREAD

**Issue by amorfuss** [caelum/mamute#119]
Creating an invalid tag when posting a question should throw error instead of directing to a new window.

![invalid tag](https://cloud.githubusercontent.com/assets/9544082/4893860/90ca9750-63c8-11e4-8e89-985544cd9f46.png)

**Comment by MatejBalantic** [comment]
This could be solved via https://github.com/caelum/mamute/pull/135 as it removes the need to validate tags in overall.

**Comment by xdarklight** [comment]
This is how it looks with current git master when I enter an invalid tag and submit the question:
![snapshot_n30551](https://cloud.githubusercontent.com/assets/5102713/13553906/26269f64-e399-11e5-9d4c-754dbad74559.png)

Looks like this bug has been fixed at some point

**Comment by felipeweb** [comment]
closing here
