### ISSUE TITLE
Server validations are leaking `ValidationException`

### ISSUE THREAD

**Issue by nykolaslima** [caelum/mamute#121]
For reproduce the error:
Try to signup with a password with less then 6 characters, disabling client-side validation.
Server will validate it and when it tries to redirect back to signup form, the `ValidationException` is leaked and this results in a broken page:
```
HTTP ERROR 400

Problem accessing /cadastrar. Reason:

    there was conversion errors, check your request!
```

**Comment by leocwolter** [comment]
Since we got no answer, I'm closing the issue. 
Please, tell us if you are still having this problem
