### ISSUE TITLE
Creating a snapshot breaks the whole project

### ISSUE THREAD

**Issue by MatejBalantic** [caelum/mamute#129]
Due to the clean:after step in Gruntfile, and due to the fact that the .jsp files and tags are being moderated in the source folder, the whole project breaks after you run ``mvn clean package -DskipTests``. That's fine if you just copy project files onto the server and run it there each time you want to deploy.

I would however expect that I am able to run the package, take the WAR and still be able to do that again, without checking out the whole source.

Currently, the whole asset/ folder gets deleted and all files gets minimized and uglified in their original location, rendering project useless. 

Is there any reason you decided for that approach?

Also: do you mind if I create a pull request in which I delete all the files that are on .gitignore list from the repo (i.e. css/ img/ etc)? It's weird setup and it caused initial confusion for me, as lots of files were changed in repo after I ran package.

**Comment by leocwolter** [comment]
You should run scripts/mvn-package.sh instead :) It will run mvn package in a separated temp folder

**Comment by MatejBalantic** [comment]
Oh, now I feel dumb, fair enough :) What about removing .gitignored files from repo? Any reason they are there?

**Comment by leocwolter** [comment]
They are probably generated by grant and imported at your page. But since it is generated each time it makes no sense to keep it on git. Does it make sense?

**Comment by leocwolter** [comment]
Check that comment at Gruntfile.js:
```
/* 
/webapp/assets -> before build
	 -> /grunt-ignore -> assets that will just be copied to production without any modifications (modify them freely)
     -> /js -> js at development (modify them freely)
     -> /less -> less (modify them freely)
     -> /generated-css -> css processed from less + ignored css (these are generated automatically, please don't touch them)
/webapp/{css/js/imgs/font} -> after all the build, production assets (these are generated automatically, please don't touch them)
*/
``´

**Comment by MatejBalantic** [comment]
@leocwolter , my point exactly. What I am proposing is removing those file from git repo entirely, as they are generated on each run anyway.  They are currently tracked by git: https://github.com/caelum/mamute/tree/master/src/main/webapp/imgs

**Comment by leocwolter** [comment]
Aw, ok, I got it. I thought it was already that way :) Sure, it makes sense

**Comment by MatejBalantic** [comment]
OK, closing for now, will prepare pull request with this and couple of others in next days :)

**Comment by csokol** [comment]
Just make sure to split your code in small PR's if possible instead of a
huge PR that is hard to code review.

**Comment by MatejBalantic** [comment]
absolutely
