### ISSUE TITLE
how to update mamaute tables?

### ISSUE THREAD

**Issue by dshetyo** [caelum/mamute#137]
i am getting following error 
Error in running mamute : Unknown column 'na2_.lastUpvote' in 'field list'

how do i run schema migration? 

details at http://meta.mamute.org/342-error-in-running-mamute--unknown-column-na2_lastupvote-in-field-list

**Comment by dshetyo** [comment]
Solved the issue by executing SchemaUpdateGenerator and then executing Main class.

Note you may need to mark migration folder as src folder, if u are using eclipse

**Comment by csokol** [comment]
thanks for reporting @dshetyo, I'm closing this issue, ok?
