### ISSUE TITLE
No code documentation

### ISSUE THREAD

**Issue by rschwietzke** [caelum/mamute#142]
Please add proper code documentation (Javadoc) as well as inline comments. If you want to invite others more actively to contribute as well as contribute high quality code, proper documentation lowers risk, enhances contribution speed as well as showcases your programming skills much better.

**Comment by csokol** [comment]
Hi Rene! Thanks for the suggestion! Are there any specific classes that you
need to understand? You can also take a look at our unit tests to
understand how things work...

**Comment by rschwietzke** [comment]
We started to use Mamute or at least are evaluating it. While browsing the code, just for fun. I saw that barely any comment or Javadoc entry is made. We are a QA company, hence this is the first thing that lowers the trust in the codebase, hence my comment. Overall the first impression is good, while build and setup where hard and some minor bugs popped up. I think @wurzelkuchen will return some feedback soon. Thanks.

**Comment by leocwolter** [comment]
Hi, @rschwietzke , could you open some issues for us to solve those bugs and make the setup easier? That would be awesome!

About the documentation, we try our best to make the code understandable without any javadoc required, if you find some piece of code that you couldn't understand, please tell us and we will be very happy to add the required documentation and help you out!

Thanks for the feedback.
