### ISSUE TITLE
How to setup gmail in vraptor

### ISSUE THREAD

**Issue by pbrianmackey** [caelum/mamute#144]
I am able to send mail using ssmtp through a gmail account.  Setting this up in developer.configuration is not working in mamute.  I am subscribed to a post and I made a change to the answer and did not get an email.

vraptor.simplemail.main.server = smtp.gmail.com
vraptor.simplemail.main.port = 587
vraptor.simplemail.main.tls = true
vraptor.simplemail.main.username = email@gmail.com
vraptor.simplemail.main.password = password
vraptor.errorcontrol.error.subject = Production error at Mamute
vraptor.simplemail.send_real_email = true

**Comment by csokol** [comment]
Hi @pbrianmackey,

I think you must force vraptor-simplemail (the plugin we are using to deliver emails) to actually send the emails in development environment. Try adding this property in your development.properties:

```
vraptor.simplemail.send_real_email = true
```

**Comment by ot-brian-mackey** [comment]
Thanks for the reply.  This has already been added.  Please look at the last line in my original post.

**Comment by csokol** [comment]
Sorry, is your file named developer.properties or development.properties?
The correct one is development.properties...

**Comment by ot-brian-mackey** [comment]
That is a type-o on my part.  It is development.properties.  I have other properties such as

```xml
feature.facebook.login = false
```
and it does take effect.

**Comment by leocwolter** [comment]
Closing, thanks!
