### ISSUE TITLE
Improvement allow Question and Answer Delete

### ISSUE THREAD

**Issue by pbrianmackey** [caelum/mamute#145]
I made myself a moderator and I cannot Delete even my own answers.  This is a pretty important feature.

**Comment by monitorjbl** [comment]
You can flag answers and questions as a moderator, which hides them from normal users. There isn't a complete delete feature, as the flagging function preserves the history of the post.

**Comment by pbrianmackey** [comment]
That gets me a little ways there.  I can't flag my own posts.

**Comment by leocwolter** [comment]
This was implemented by @csokol at https://github.com/caelum/mamute/pull/154
Thanks!
