### ISSUE TITLE
Help setting up log4j

### ISSUE THREAD

**Issue by ot-brian-mackey** [caelum/mamute#146]
log4j is not working.  Error:  

```
log4j:WARN No appenders could be found for logger (com.mchange.v2.log.MLog).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
```

Configuration of development.properties:
```
#log4j
# Set root logger level to DEBUG and its only appender to A1.
log4j.rootLogger=DEBUG, A1

# A1 is set to be a ConsoleAppender.
log4j.appender.A1=org.apache.log4j.ConsoleAppender

# A1 uses PatternLayout.
log4j.appender.A1.layout=org.apache.log4j.PatternLayout
log4j.appender.A1.layout.ConversionPattern=%-4r [%t] %-5p %c %x - %m%n

I'm getting that error and no output to console or in mamute/logs/logs

**Comment by leocwolter** [comment]
Mamute already provide an [log4j.xml](https://github.com/caelum/mamute/blob/master/src/main/resources/log4j.xml) for you to use. Make sure it is on your classpath.

The file you used(development.properties) is exclusive for vraptor-environment properties, thats why it didn't work

**Comment by siddjain** [comment]
I also get this error and log4j.xml is present on the classpath at WEB-INF/classes/log4j.xml
