### ISSUE TITLE
Security issue: User is able to upload any file as his avatar

### ISSUE THREAD

**Issue by MatejBalantic** [caelum/mamute#158]
Steps to reproduce:

1. Go to your profile
2. Click edit profile
2. Try to upload a dangerous file as your avatar

This works with uploading a video, image, or even .dmg

This really should have some sanity checks (size, extension, mime type?), otherwise our portals could become illegal upload services :)

**Comment by leocwolter** [comment]
Great observation, @MatejBalantic , thanks! I'll be labeling that as critical
@csokol
