### ISSUE TITLE
Security issue: server restart possible by invoking URL call

### ISSUE THREAD

**Issue by MatejBalantic** [caelum/mamute#172]
By invoking URL call ``/vraptor/restart/`` any anonymous user can restart any Mamute instance.

This should not be allowed due to obvious security implications (server overload, data loss). 

What is the reason for this call being allowed?
https://github.com/caelum/mamute/blob/master/src/main/java/br/com/caelum/vraptor/server/VRaptorServer.java#L66

**Comment by csokol** [comment]
Well observed, @MatejBalantic! Thanks!
