### ISSUE TITLE
Create a docker container for Mamute for easy evaluation of platform

### ISSUE THREAD

**Issue by bradparks** [caelum/mamute#192]
Hey! It'd be great if there was a docker container for Mamute, to allow people to easily spin up a mamute instance and evaluate it.

**Comment by kullervo16** [comment]
I created a simple image based on the release version 1.3.0 (in a centos 7 container with openjdk 1.7.0) Feel free to comment there when you miss something in the container or you have any trouble with it.

https://hub.docker.com/r/kullervo16/mamute/

(I lack the reputation to answer this in the forum...)

**Comment by bradparks** [comment]
cool.... thanks a bunch... much appreciated!

**Comment by csokol** [comment]
Awesome, @kullervo16!

Can you open a PR with the Dockerfile your created? 

Maybe we should also provide a Docker Compose yml together with our Dockerfile linking Mamute to a MySQL or MariaDB container. We can even improve it in the future by adding alternative setups with an standalone solr container, for example.

**Comment by xdarklight** [comment]
A full Docker setup was committed in 8c4f7b15fc07d61cc439d44d37b4e62fdcb2e95b
@bradparks: can you close this BR if that commit has everything you want?

**Comment by bradparks** [comment]
thanks!
