### ISSUE TITLE
Emails not working in development environments

### ISSUE THREAD

**Issue by xdarklight** [caelum/mamute#197]
Even if configured correctly, emails are always handled by MockMailer in development environments.
This seems to be caused by caelum/vraptor-simplemail#26

We first need to get the fix applied to vraptor-simplemail, then we need a new release there and finally we have to update the dependency in mamute.

**Comment by xdarklight** [comment]
@csokol any chance you can look at caelum/vraptor-simplemail#26 ?

**Comment by xdarklight** [comment]
@guilhermesilveira could you please release a new version of vraptor-simplemail (VRaptor4Version branch)?
Then we can finally fix this Mamute bug!

**Comment by Turini** [comment]
@xdarklight I just left a comment on caelum/vraptor-simplemail#26.
I'll release a new version as soon as it's decided

**Comment by Turini** [comment]
@xdarklight @JamesSullivan it's done, vraptor-simplemail 4.1.0-rc3 will be available in a few hours

**Comment by xdarklight** [comment]
Fixed with caelum/vraptor-simplemail@e803d24a7b2f080b9d0afcf67acf8acb0449f887 / 7dc8d9085fb99fd19e4895085731ed63faa0fbef
