### ISSUE TITLE
Deploy mamute on Heroku or Openshift

### ISSUE THREAD

**Issue by khajavi** [caelum/mamute#206]
Any one have experience on deploying Mamute on Heroku or Openshit?
How can I do that? 
I can run maven based project on heroku, but mamute project is based on grunt and maven together. I have no idea how to install node.js and npm on heroku.

**Comment by kullervo16** [comment]
we are running mamute on Openshift v3, so based on a docker container. You can find my docker container on dockerhub (https://hub.docker.com/r/kullervo16/mamute/). It contains a simple script to pass environment variables that you can specify in your Openshift deployment configuration to the container. If you need full control, just create a new image based on that one and replace the properties with your values.

There is also a new pull request for a docker compose setting, but if you have openshift, you can already specify your database in either your POD definition or link to another container via the variables.

**Comment by felipeweb** [comment]
closing here, if you want feel free to reopen
