### ISSUE TITLE
Is anybody maintaining a more bleeding edge fork?

### ISSUE THREAD

**Issue by JamesSullivan** [caelum/mamute#219]
An admittedly quick look shows only an update to the version number and very minor css change in the last six months despite a number of outstanding pull requests. I was just wondering if anybody is maintaining a more up-to-date fork (updating dependencies and including some of the more reasonable pull requests)?

**Comment by csokol** [comment]
Hi James,

I don't know if there's any active mamute fork being developed.

I know that things are a little slow at mamute's github, but I will try to
keep up with the review of the pending PR's.

In the meanwhile, I talk to the guys at Caelum (the owners of mamute) to
check if we can get more contributors to this project.

Please don't lose your faith on mamute, let's try to improve the community
around it :)

Em qui, 14 de jan de 2016 00:16, James Sullivan <notifications@github.com>
escreveu:
