### ISSUE TITLE
Unicode problem in forgot email 

### ISSUE THREAD

**Issue by khajavi** [caelum/mamute#223]
I've these variables in fa_IR messages:

```
# FORGOT PASSWORD
forgot_password_mail = گذرواژه‌تان را تغییر دهید
forgot_passsword_mail.hello = سلام {0},
forgot_password_mail.message = برای تغییر گذرواژه <a href="{0}">اینجا کلیک کنید</a>
forgot_password_mail.warn = اگر درخواستی برای تغییر گذرواژه نداده‌اید، این رایانامه را نادیده بگیرید.
```

But forgot email doesn't send in utf-8 format. I think it is because of Freemaker and vraptor-mail component. I didn't found the source of problem. If any one know, help me to create the pull request for this issue.

![email-mamute](https://cloud.githubusercontent.com/assets/235974/12471291/6e6c8e74-c011-11e5-9820-35299675697c.png)

**Comment by xdarklight** [comment]
I think this is related to #190

**Comment by khajavi** [comment]
As @xdarklight mentioned this issue is related to #190 so I close this issue.
