### ISSUE TITLE
Web Server/ Web Application Vulnerable to Cross-Site Scripting Attacks

### ISSUE THREAD

**Issue by superm1a3** [caelum/mamute#225]
Recently our IT department found a Cross-Site Scripting vulnerability on our Mamute server during one of the Qualys scans. Please see the attached file for more information. Our Mamute server is running the 1.4.0 release.

[mamute-xss.txt](https://github.com/caelum/mamute/files/116070/mamute-xss.txt)

**Comment by felipeweb** [comment]
@superm1a3  i'm closing here , the PR #234  prevent the attack, feel free to reopen if you have any doubts

**Comment by superm1a3** [comment]
@felipeweb How can CORS prevent XSS? Can you explain more? They seem unrelated. (http://security.stackexchange.com/questions/108835/how-does-cors-prevent-xss)
