### ISSUE TITLE
How to make mamute work with non root user?

### ISSUE THREAD

**Issue by siddjain** [caelum/mamute#236]
The setup instructions say:

> First of all, you need to setup an MySQL database. The default database name is mamute_development, the username is root and the password must be blank.

I don't want to use root user. How can I make it work with a non-root user that also has a non-blank password?

**Comment by JamesSullivan** [comment]
This may be a better question for http://meta.mamute.org/

If you want to change the user name/password for MySQL in development it can be changed by modifying it in the mamute/src/main/resources/development/hibernate.cfg.xml file.  Of course on the MySQL side you need to 'create database mamute_development' and then create a user with permission to use that database and the same id/password as you put in the hibernate.cfg.xml file.

**Comment by siddjain** [comment]
Thanks. This is exactly what I needed. This info ought to be there in the instructions on the main page.

Date: Thu, 18 Feb 2016 14:38:39 -0800
