### ISSUE TITLE
why exactly 3 persistence class objects will created after creating SessionFactory object.

### ISSUE THREAD

**Issue by Gyana2054** [caelum/mamute#240]
Configuration cfg=new Configuration();
cfg.configure();
...... at this point the default constructor of persistence class will not call.That means no instance will create for persistence class

but after creating Sessionfactory object i.e

Configuration cfg=new Configuration();
cfg.configure();
SessionFactory sf=cfg.buildSessionFactory();
....default construct will call 3 times exactly so the question is why exactly 3 persistence class objects will created after creating SessionFactory object.

**Comment by felipeweb** [comment]
The project have 3 hibernate.cfg file, this create 3 persistence class
