### ISSUE TITLE
A little marketing for mamute

### ISSUE THREAD

**Issue by ramswaroop** [caelum/mamute#273]
Hi,

I appreciate the work you guys are doing so thought of helping you a bit. Have created a [subreddit for mamute](https://www.reddit.com/r/mamute/) as well as I made a post on [Java subreddit](https://www.reddit.com/r/java/comments/4y6k82/a_nice_opensource_replica_of_stackoverflow_built/) which received a very good response.

So, you might see a spike in the number of stars now. Cheers!

**Comment by ramswaroop** [comment]
And please do tell me your reddit creds, will make you guys the moderator of mamute subreddit.

**Comment by code4passion** [comment]
+1

**Comment by csokol** [comment]
Awesome! I'm not a reddit regular user, but my id is chicosokol, @ramswaroop.

I'll close here, ok?

**Comment by ramswaroop** [comment]
Have sent u an invite. Cheers!
