### ISSUE TITLE
A step-by-step guide to install SSL certificate in mamute

### ISSUE THREAD

**Issue by ramswaroop** [caelum/mamute#282]
Any links/references would suffice.

**Comment by csokol** [comment]
@ramswaroop my advice is that you shouldn't care about solving that at the application server level. The best way to setup SSL is by creating a reverse proxy on top of the application (could be nginx or httpd) and setup the SSL there.

Some useful references for nginx setup:
https://www.digitalocean.com/community/tutorials/how-to-configure-nginx-as-a-web-server-and-reverse-proxy-for-apache-on-one-ubuntu-16-04-server
https://www.digitalocean.com/community/tutorials/how-to-create-an-ssl-certificate-on-nginx-for-ubuntu-14-04

**Comment by ramswaroop** [comment]
@csokol Thanks for the reply. Any reasons as to why not in the application server? _Sorry if I am being stupid, new to this SSL thing._
