### ISSUE TITLE
Error displaying permission.rule.inactivate_question in about page

### ISSUE THREAD

**Issue by arnauldvm** [caelum/mamute#287]
In WEB-INF/jsp/navigation/about.jsp @44

I guess INACTIVE_QUESTION shoudl be replaced by INACTIVATE_QUESTION?
(as per src/main/java/org/mamute/auth/rules/PermissionRules.java)

**Comment by csokol** [comment]
You're right, @arnauldvm, can you open a PR fixing it?

**Comment by arnauldvm** [comment]
PR created: #288
