### ISSUE TITLE
Como configurar mamute na porta 80

### ISSUE THREAD

**Issue by vicenthy** [caelum/mamute#290]
estou tentando configurar o mamute na porta 80, porém quando ativo essa configuração atras do export PORT=80 ele não inicia da erro "socket access denied" acredito que seja o quartz.

Como faz pra configurar corretamente.

obs: as duas portas estão liberadas no meu server.

**Comment by csokol** [comment]
Oi @vicenthy, a porta 80 é restrita para usuários comuns em linux/unix. Você tentou subir o servidor como root ou com sudo?

Estou fechando a issue pois não é relacionado ao mamute em si, ok?

**Comment by vicenthy** [comment]
isso foi a primeira coisa que pensei, quando tive esse problema e por incrível que parece eu rodei o server com sudo e não funcionou, isso a uns dias atrás agora hoje me entrei como root no sistema e rodei tudo como root e agora funcionou.
