### ISSUE TITLE
Configuração envio de email

### ISSUE THREAD

**Issue by vicenthy** [caelum/mamute#291]
Boa tarde, 

eu segui e configuração do servidor de email, porém os envios não estão funcionando.

minha configuração no production.properties

vraptor.simplemail.main.server = smtp.gmail.com
vraptor.simplemail.main.port = 587
vraptor.simplemail.main.tls = true
vraptor.simplemail.main.username = sigaoadvpl.resposta@gmail.com
vraptor.simplemail.main.password = XXXXXXXX
vraptor.errorcontrol.error.subject = Production error at SigaOAdvpl

**Comment by hugoroger** [comment]
Esse app não é mais mantido. Vc precisa debugg tudo internamente.

**Comment by vicenthy** [comment]
Ok, agradeço feedback.

**Comment by csokol** [comment]
Qual erro está acontecendo? Pode mandar os logs da aplicação?

**Comment by vicenthy** [comment]
consegui corrigir, mas estou com uma dúvida.  quando o usuário cria a postagem ele só recebe o email se ele se escrever para receber todas as postagens?
