### ISSUE TITLE
deletar post

### ISSUE THREAD

**Issue by vicenthy** [caelum/mamute#292]
como faço para deletar post? preciso fazer uma limpeza na base.

**Comment by csokol** [comment]
Como admin não é possível deletar ou ao menos esconder uma pergunta?

**Comment by vicenthy** [comment]
não.

**Comment by vicenthy** [comment]
eu só tenho acesso como moderador, como faço pra ter acesso como admin?

**Comment by vicenthy** [comment]
é preciso habilitar algumas configurações.

#authors can delete their questions (as long there's no answers/comments) and moderators can delete whole threads
deletable.questions = false
#authors/moderators can delete answers (as long there's no comments)
deletable.answers = false
#authors/moderators can delete comments
deletable.comments = false
#moderators can delete users
deletable.users = true
