### ISSUE TITLE
improvements in moderation -5 points unable to post

### ISSUE THREAD

**Issue by defaultbr** [caelum/mamute#32]
Last week we saw a stupid guy creating a useless questions and answers in a huge number of topic at the GUJ Questions.

Even after receiving several negative points, he was still allowed to create useless posts, so i think  would be good to create a blocklist for users to at least -5 points, automatically placed on this list after reached this negative value, and he will not be allowed to post comments, answers , scoring, flag, edit, etc., read only state, until some moderator remove the user from blocklist and set his score to 0 points (can be auto setted when removed from list)

**Comment by leocwolter** [comment]
I'm not sure if this feature is already up. @csokol ?

**Comment by felipeweb** [comment]
this feature is already up closing here
