### ISSUE TITLE
improvements in answers not allowed to create answer if under 10 points(in their own question)

### ISSUE THREAD

**Issue by defaultbr** [caelum/mamute#33]
people are still creating answers when they just want to add a comment or information to the Original Question, normally they have under 10 points, normal, since they dont know how to use the tool BUT, they can be blocked(if they have under 10 points) to create answers in their own question, they can create answers in other user question(even under 10 points) or in their own question when more than 10 points, if they are under 10 and in their question screen, if they click in "ANSWER"

a screen or tooltip show up then something similar to this:

"Hi user you have under 10 points, so you cant create answer in your own question, you can answer other people questions or wait until you reach 10 points, if you have the answer or another comment/information to add, just edit your question(click in edit button) or add it like a comment(click in add a comment)"

**Comment by leocwolter** [comment]
This is already implemented, I'm closing this issue
