### ISSUE TITLE
Image upload

### ISSUE THREAD

**Issue by leocwolter** [caelum/mamute#6]
The user should be able to choose between upload a image or use gravatar.
Currently gravatar is the only option.

**Comment by roanosullivan** [comment]
+1 Not all environments have access to the Gravatar service.

**Comment by leocwolter** [comment]
Hi @roanosullivan, do you have interest in implementing that? It would be awesome :)

**Comment by roanosullivan** [comment]
I'll add it to my personal backlog. Not sure when I'll actually get to it though.

**Comment by leocwolter** [comment]
Closed by https://github.com/caelum/mamute/pull/155
